<?php

/**
 * @file
 * Implements the drupal hooks required for statehandler.
 */

/**
 * Implements hook_library().
 *
 * @return
 *  A library array for statehandler
 */
function statehandler_library() {
  $libraries = array();
  $jspath = drupal_get_path('module', 'statehandler') . '/js/';

  $libraries['statehandler'] = array(
    'title' => 'Statehandler',
    //'website' => 'https://github.com/balupton/History.js/',
    'version' => '7.x-1.x',
    'js' => array($jspath . 'statehandler.js' => array()),
    'dependencies' => array(
      // require the history.js library from history_js
      array('history_js', 'history.js'),
      array('statehandler', 'statehandler.class')
    )
  );

  $libraries['statehandler.class'] = array(
    'title' => 'StateHandler Class',
    'version' => '7.x-1.x',
    'js' => array($jspath . 'statehandler.class.js' => array())
  );

  return $libraries;
}

/**
 * Implements hook_init().
 */
function statehandler_init() {
  // Add settings to js so stateHandler knows how to interface with History.js.
  $implementation = variable_get('history_js_implementation', 'jquery');
  drupal_add_js(array('stateHandler' => array('history_js_implementation' => $implementation, 'plugins' => array())), 'setting');
}
