<?php

/**
 * @file
 * Implements the drupal hooks required for example_statehandler.
 */

/**
 * Implements hook_library().
 *
 * @return
 *  A library array for example_statehandler.
 */
function example_statehandler_library() {
  $libraries = array();
  $jspath = drupal_get_path('module', 'example_statehandler') . '/js/example_statehandler.js';

  $libraries['example_statehandler'] = array(
    'title' => "Example Statehandler",
    'version' => '7,x-1.x',
    'js' => array($jspath => array(
      'dependencies' => array(
        array('statehandler' => 'statehandler')
      )
    ))
  );

  return $libraries;
}

/**
 * Implements hook_init();
 */
function example_statehandler_init() {
  drupal_add_library('example_statehandler', 'example_statehandler');
}
